[versions]
agp = "8.4.0"
kotlin = "1.9.0"
maven-publish = "1.3.0"
jreleaser = "1.14.0"

core-ktx = "1.13.1"
appcompat = "1.7.0"
material = "1.12.0"
nicestarratingview = "1.0.3"

minSdk = "21"
compileSdk = "34"
targetSdk = "34"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
nicestarratingview = { group = "io.github.dmitrytsyvtsyn", name = "nicestarratingview", version.ref = "nicestarratingview" }

[plugins]
android =  { id = "com.android.application", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
maven-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "maven-publish" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }